# 网关服务
server:
  port: 3300
  environment: development
  prefix: # 路径前缀

# 微服务
microservices:
  base:
    server:
      port: 3301
    config:
      transport: 0
      options:
        host: localhost
        port: 3301

# 数据库
db:
  base:
    type: 'mysql'
    host: 'localhost'
    port: 3306
    username: 'root'
    password: ''
    database: 'base'
    synchronize: true

# redis
redis:
  host: '127.0.0.1' # 连接本地 Redis 实例
  port: 6379 # Redis 默认端口
  password: '' # Redis 的认证密码
  db: 0 # 使用 Redis 的第 0 号逻辑数据库
  ttl: 30000 # 默认缓存过期时间为 30天 毫秒（单位毫秒）30*24*60*60*1000

# 多语言
i18n:
  fallbackLanguage: 'zh'
  path: 'i18n/'

# jwt
jwt:
  secret: ''
  expiresIn: '30d'

# 阿里云
aliyun:
  # oss子账户
  oss:
    AccessKeyId: ''
    AccessKeySecret: ''
  # sms子账户
  sms:
    AccessKeyID: ''
    AccessKeySecret: ''

# 日志
logger:
  # 日志文件的名称格式
  filename: 'application-%DATE%.log'
  # 日期的格式化样式，这决定了文件名中日期的显示方式
  datePattern: 'YYYY-MM-DD'
  # 日志的存放目录
  dirname: 'logs'
  # 是否压缩（归档）旧的日志文件
  zippedArchive: true
  # 单个文件的最大大小，会根据这个大小自动分割日志
  maxSize: '20m'
  # 保存日志文件的最长时间或文件数量的上限
  maxFiles: '14d'

# 日志存储文件路径
logsPath: logs
